name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.21'

      
      - name: Install golangci-lint
        run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.2
  
      - name: Run golangci-lint
        run: golangci-lint run ./...
  
      - name: Install package dependencies
        run: go mod tidy
    
      - name: Run tests
        run: go test -v ./...
  
      - name: Generate and publish Godoc
        run: |
            go install golang.org/x/tools/cmd/godoc@latest
            mkdir -p godoc
            godoc -http=:6060 -index &
            sleep 20 # Подождите, пока godoc запустится
            wget -r -np -P godoc -nH --cut-dirs=1 -E http://127.0.0.1:6060/pkg/
            pkill godoc # Завершить процесс godoc после скачивания документации
  
      - name: Push GoDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./godoc

      - name: Install dependencies for semantic-release
        run: |
          if [ -f package.json ]; then 
            npm install 
          fi

      - name: Install semantic-release
        run: npm install -g semantic-release

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release